---
title: "Data Manipulation with dplyr"
author: "Junxian Chen (jc5314)"
date: "9/19/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

options(tibble.print_min = 3)

litters_data = read_csv("./FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```

## Selecting

```{r}
select(litters_data, group, litter_number, starts_with("pups"))

select(litters_data, litter_number, group, everything())

# remove variable
select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)

# renmae the variable
select(litters_data, GROUP = group, litter_number)

# just rename the variable but no selection
rename(litters_data, GROUP = group)
```

## Filtering

```{r}
filter(litters_data, group == 'Con7')

filter(litters_data, pups_born_alive < 6)

# group == con7 and/or con8
filter(litters_data, group %in% c("Con7", "Con8"))

filter(litters_data, group == 'Con7' | group == 'Con8')

filter(litters_data, gd0_weight < gd18_weight)

# don't do this:
filter(litters_data, !is.na(gd0_weight))

# recommend:
drop_na(litters_data, gd0_weight)
```

