---
title: "Data Import"
author: "Junxian Chen (jc5314)"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Load in the dataset

```{r, collapse = TRUE}
# read in a dataset
litters_data = read_csv(file = "./FAS_litters.csv")

names(litters_data)

litters_data = janitor::clean_names(litters_data)
names(litters_data)

skimr::skim(litters_data)
```

## Load in another dataset

```{r}
pups_data = read_csv(file = "./FAS_pups.csv")
names(pups_data)

pups_data = janitor::clean_names(pups_data)
names(pups_data)
```

```{r}
litters_data = read_csv(file = "./FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

## Column parsinh

```{r}
litters_data = read_csv(
  file = "./FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)

tail(litters_data)
```

## Read in an excel file

```{r}
library(readxl)

mlb11_data = read_excel("./mlb11.xlsx", n_max = 20)
#mlb11_data = read_excel(
#  path = "./mlb11.xlsx",
#  sheet = xxx,
#  range = "A1:B7")

head(mlb11_data, 5)
```

## Read in SAS 

```{r}
library(haven)

pulse_data = read_sas("./public_pulse_data.sas7bdat")

head(pulse_data, 5)
```

